// Product Data
const PRODUCTS = [
  {
    id: 1,
    name: "Silk Bias Slip Dress",
    price: 245,
    category: "dresses",
    isNew: true,
    color: "#C9B89A",
    colorName: "Sand",
    description: "A fluid bias-cut slip dress in 100% silk charmeuse. Falls beautifully to the midi length with adjustable straps and a subtle slit at the hem.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Silk Charmeuse",
    care: "Dry clean or hand wash cold"
  },
  {
    id: 2,
    name: "Linen Wide-Leg Trouser",
    price: 185,
    category: "bottoms",
    isNew: true,
    color: "#E8E0D5",
    colorName: "Ivory",
    description: "High-waisted wide-leg trousers in organic Irish linen. A pleated front and cropped ankle length make this the summer staple.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Irish Linen",
    care: "Machine wash cold, tumble dry low"
  },
  {
    id: 3,
    name: "Merino Turtleneck",
    price: 145,
    category: "tops",
    isNew: true,
    color: "#4A4A4A",
    colorName: "Charcoal",
    description: "A fine-gauge merino wool turtleneck that layers effortlessly. Soft, temperature-regulating, and timeless.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "100% Extra Fine Merino Wool",
    care: "Hand wash cold, lay flat to dry"
  },
  {
    id: 4,
    name: "Structured Blazer",
    price: 320,
    category: "outerwear",
    isNew: true,
    color: "#2C2C2C",
    colorName: "Black",
    description: "A sharply tailored blazer in Italian wool-blend suiting. Single-button closure, flap pockets, and a slightly relaxed silhouette.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "70% Wool, 30% Polyester",
    care: "Dry clean only"
  },
  {
    id: 5,
    name: "Open-Knit Cardigan",
    price: 195,
    category: "tops",
    isNew: false,
    color: "#D4C4A8",
    colorName: "Oat",
    description: "A relaxed open-knit cardigan in a cotton-linen blend. Oversized fit, drop shoulders, and deep pockets.",
    sizes: ["XS/S", "M/L", "XL/XXL"],
    material: "55% Cotton, 45% Linen",
    care: "Machine wash cold, reshape while damp"
  },
  {
    id: 6,
    name: "Pleated Midi Skirt",
    price: 165,
    category: "bottoms",
    isNew: false,
    color: "#8C7B6B",
    colorName: "Mocha",
    description: "A knife-pleated midi skirt in lightweight crepe. Elasticated waist for comfort, fully lined.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Recycled Polyester Crepe",
    care: "Machine wash cold"
  },
  {
    id: 7,
    name: "Cashmere Scarf",
    price: 125,
    category: "accessories",
    isNew: false,
    color: "#B8A898",
    colorName: "Stone",
    description: "A generous cashmere scarf, generously oversized for draping or wrapping. Fringe-trimmed edges.",
    sizes: ["One Size"],
    material: "100% Grade A Cashmere",
    care: "Dry clean or hand wash cold"
  },
  {
    id: 8,
    name: "Trench Coat",
    price: 480,
    category: "outerwear",
    isNew: false,
    color: "#C8A97A",
    colorName: "Camel",
    description: "The classic trench reimagined. Double-breasted, belted, with a removable wool inner layer for year-round wear.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "65% Cotton, 35% Polyester, Wool lining",
    care: "Dry clean only"
  },
  {
    id: 9,
    name: "Organic Cotton Tee",
    price: 65,
    category: "tops",
    isNew: false,
    color: "#F5F0E8",
    colorName: "Cream",
    description: "The perfect everyday tee. A slightly boxy fit in heavyweight organic cotton with a crew neck.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "100% Organic Cotton",
    care: "Machine wash warm"
  },
  {
    id: 10,
    name: "Wrap Maxi Dress",
    price: 215,
    category: "dresses",
    isNew: false,
    color: "#7A6B8A",
    colorName: "Plum",
    description: "A fluid wrap-style maxi dress in a matte jersey. Adjustable tie at the waist, V-neckline.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "95% Viscose, 5% Elastane",
    care: "Machine wash cold"
  },
  {
    id: 11,
    name: "Leather Mini Bag",
    price: 285,
    category: "accessories",
    isNew: false,
    color: "#3A2E26",
    colorName: "Espresso",
    description: "A compact crossbody in full-grain vegetable-tanned leather. Magnetic closure, adjustable chain strap.",
    sizes: ["One Size"],
    material: "Full-grain leather, brass hardware",
    care: "Condition with leather cream"
  },
  {
    id: 12,
    name: "Cropped Utility Jacket",
    price: 265,
    category: "outerwear",
    isNew: false,
    color: "#556B2F",
    colorName: "Olive",
    description: "A cropped utility jacket in cotton canvas. Multiple pockets, a relaxed fit, and a detachable belt.",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Cotton Canvas",
    care: "Machine wash cold"
  }
];
